cursor #f5dfcc
cursor_text_color #d8c3b1

foreground            #f5dfcc
background            #1c1107
selection_foreground  #432c06
selection_background  #e6c08d
url_color             #ffb86e

color0   #1c1107
color1   #ff695f
color2   #86ff6e
color3   #ffe35f
color4   #f2a14c
color5   #763c00
color6   #ffb86e
color7   #fff6ed
color8   #a59e97
color9   #ff9892
color10  #aaff99
color11  #ffed99
color12  #ffc283
color13  #ffcd99
color14  #ffdfbd
color15  #fffbf7
